### ISSUE TITLE
When running demo_track.py,  an error is reported:ModuleNotFoundError: No module named 'yolox_dancetrack_val_Hybrid_sort'

### ISSUE THREAD

**Issue by liguo668** [ymzis69/HybridSORT#13] opened 2023-09-01 07:27 UTC
The detailed error is reported as:
Traceback (most recent call last):
  File "d:\mot_projects\hybirdsort\yolox\exp\build.py", line 13, in get_exp_by_file
    current_exp = importlib.import_module(os.path.basename(exp_file).split(".")[0])
  File "C:\Users\liguo\miniconda3\envs\deepsort\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'yolox_dancetrack_val_Hybrid_sort'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/demo_track.py", line 351, in <module>
    exp = get_exp(args.exp_file, args.name)
  File "d:\mot_projects\hybirdsort\yolox\exp\build.py", line 51, in get_exp
    return get_exp_by_file(exp_file)
  File "d:\mot_projects\hybirdsort\yolox\exp\build.py", line 16, in get_exp_by_file
    raise ImportError("{} doesn't contains class named 'Exp'".format(exp_file))
ImportError: exps/example/mot/yolox_dancetrack_val_Hybrid_sort.py doesn't contains class named 'Exp'

Hopefully someone can help with this, thanks！！！

**Comment by ymzis69** [comment] 2023-09-01 08:45
Sorry, this was our mistake because we uploaded the wrong version of README.md. Please run the code according to this version of the README.md: https://github.com/ymzis69/HybirdSORT/tree/6101e1b225cb4b860f914049f9cccc0cd4538075, as ‘yolox_dancetrack_val_Hybrid_sort.py’ is not present in our exp file. We will have this bug fixed within the next two days. We apologize again for the inconvenience caused by the photo taken for you.

**Comment by liguo668** [comment] 2023-09-02 10:38
> Sorry, this was our mistake because we uploaded the wrong version of README.md. Please run the code according to this version of the README.md: https://github.com/ymzis69/HybirdSORT/tree/6101e1b225cb4b860f914049f9cccc0cd4538075, as ‘yolox_dancetrack_val_Hybrid_sort.py’ is not present in our exp file. We will have this bug fixed within the next two days. We apologize again for any inconvenience this may have caused you.

Okay. Thanks for your reply.

**Closed** 2023-09-03 13:59 UTC
